services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy_firewall
    restart: unless-stopped
    ports:
      # Cổng 80 cho Sinkhole trên LAN
      - "80:80"
      # Cổng 53 cho DNS thô trên LAN
      - "53:53/udp"
      - "53:53/tcp"
      # Cổng 8081 cho trang hướng dẫn trên LAN
      - "8081:8081"
    networks:
      - nt140-net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./sinkhole:/var/www/sinkhole
      - ./dashboard:/app/dashboard
      - ./clients:/app/clients
      - ./setup:/app/setup
      - caddy_data:/data # Lưu trữ dữ liệu Caddy (bao gồm cả chứng chỉ nội bộ)
    healthcheck:
      test: ["CMD", "caddy", "list-routes"]
      interval: 10s
      timeout: 5s
      retries: 5

  dns_server:
    container_name: dns_firewall_server
    restart: unless-stopped
    build:
      context: ./server
    networks:
      - nt140-net
    volumes:
      - ./server/data:/app/data # Gắn thư mục data để lưu blacklist và DB
    environment:
      # Chuyển tiếp các biến cấu hình
      - SINKHOLE_IP=${SINKHOLE_IP}
      - ROUTER_IP=${ROUTER_IP}
      - UPSTREAM_DNS_1=${UPSTREAM_DNS_1}
      - UPSTREAM_DNS_2=${UPSTREAM_DNS_2}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel run
    networks:
      - nt140-net
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      caddy:
        condition: service_healthy
  

networks:
  nt140-net:
    driver: bridge

volumes:
  caddy_data: